### PR TITLE
correct select method and add tests for it

### PR DESCRIPTION
**Pull request by thatportugueseguy**

### CODE REVIEW

**Comment by thatportugueseguy** [comment]
Tried this method and wasn't working properly. I hope this will help. :)

**Comment by yeahoffline** [comment]
thank you! feel free change the version @package.json

**Comment by KITSJoseNogueira** [comment]
Hey, I'm not sure I should be the one to do that, as you are the official contributors to the project.

just do "npm publish minor" and it will be bumped :)

Thanks

**Comment by yeahoffline** [comment]
oh great, done!

**Comment by osher** [comment]
oups. I was just about to do the same thing all over again.

When will this fix be published ?

**Comment by osher** [comment]
Ah. no. Sorry. I'm about to fix a bug in that function: should use `MockInstance.callCallback`

see  #30

**Comment by yeahoffline** [comment]
oh nice! looking forward to test it

**Pull request merged**
