### PR TITLE
Sorted Set Functions

### PR DESCRIPTION
**Pull request by grippy**
Here's a summary of changes:

- This branch implements *most* of the sorted set commands w/ tests. (See inline comments about which ones still need to be implemented)

- Adds 'sismember' for testing set membership.

- Sorted the multi command list (makes it a little easier to read).

- README updates

### CODE REVIEW

**Comment by yeahoffline** [comment]
test fail?

**Comment by grippy** [comment]
@yeahoffline Yeah the tests failed. The main issue I was having is how redis inputs and returns floats for incrby commands. For example, incrby '5.4' stores the value as '5.4000000000000004'. 
For now, I've updated the tests to stop trying to incrby using floats.

All tests pass on my localhost running x4.4.3 but are failing with travis.  https://travis-ci.org/yeahoffline/redis-mock/jobs/165615334

Looks like it's an issue with node v0.10.47. Let me see if I can debug this node version and get these to pass.

**Comment by grippy** [comment]
@yeahoffline Looks like this has the green light now.

**Comment by grippy** [comment]
@yeahoffline Anyway you can get this merged soon and push a new build to NPM?

**Comment by yeahoffline** [comment]
its done now!

**Comment by grippy** [comment]
Much obliged @yeahoffline 
Thanks!

**Pull request merged**
