### PR TITLE
Added scan command

### PR DESCRIPTION
**Pull request by turpault**
Added support for scan command

make test and make check-tests passing (except for the issues before this PR)

### CODE REVIEW

**Comment by yeahoffline** [comment]
check-tests are failing. 

`  1) keys should scan keys - *:
     Uncaught AssertionError: expected Array [] to have property length of 1 (got 0)`

**Comment by turpault** [comment]
I'll check why this does not pass the tests.

**Comment by turpault** [comment]
Fixed. The redis SCAN command is quite unpredictable.

**Comment by yeahoffline** [comment]
mhh same code? looks like tests are inconsistent

**Comment by turpault** [comment]
Actually a badly written test. redis does not guarantee the # of returned keys for a scan operation. We can only validate that we have all the keys once the scan is finished.

Previous test was working fine with the mock code, but not always with an actual redis db.
Actually that even varies with the redis db version (make check-tests was passing locally, with redis 2.8.21, which is getting a bit old).

**Pull request merged**
