### PR TITLE
ZINTERSTORE implementation added

### PR DESCRIPTION
**Pull request by DawidLoubser**
Added partial ZINTERSTORE (no custom aggregate yet, only the default SUM) + other minor fixes.

### CODE REVIEW

**Comment by yeahoffline** [comment]
you plan to fully implement ZINTERSTORE ?

**Comment by DawidLoubser** [comment]
@yeahoffline I do, when time allows :-) Also, the impl for `ZUNIONSTORE` that I contributed couple of months ago need to be completed, it also doesn't support custom aggregate yet.

Up to you if you want to wait for full implementation.

**Comment by DawidLoubser** [comment]
@yeahoffline I do, when time allows :-) Also, the impl for `ZUNIONSTORE` that I contributed couple of months ago need to be completed, it also doesn't support custom aggregate yet.

Up to you if you want to wait for full implementation.

**Comment by DawidLoubser** [comment]
BTW, do you think the Travis tests are failing because I'm using some Ecmascript 5.1 Array features that are not present in older versions of Node? What are the Node compatibility guidelines of this project? (so that I can adjust my implementation to be limited to older features)

**Comment by yeahoffline** [comment]
travis tests fail for some time now. there is a test whatever callback error i guess. no time to debug tbh

**Pull request merged**
